TOTAL_ROWS = ENV.fetch('TOTAL_ROWS') { 5 }.to_i
TOTAL_COLUMNS = ENV.fetch('TOTAL_COLUMNS') { 5 }.to_i
MOVE_STEPS = ENV.fetch('MOVE_STEPS') { 1 }.to_i

EAST = 'EAST'
WEST = 'WEST'
SOUTH = 'SOUTH'
NORTH = 'NORTH'

ALL_DIRECTIONS = [EAST, NORTH, SOUTH, WEST]

ROTATE_LEFT_SIGNAL = "LEFT"
ROTATE_RIGHT_SIGNAL = "RIGHT"
EMPTY_ROW_COLUMN_VALUE = ""

ROTATE_DIRECTIONS = {
  ROTATE_LEFT_SIGNAL => {
    EAST => NORTH,
    WEST => SOUTH,
    SOUTH => EAST,
    NORTH => WEST
  },
  ROTATE_RIGHT_SIGNAL => {
    EAST => SOUTH,
    WEST => NORTH,
    SOUTH => WEST,
    NORTH => EAST
  }
}